### ISSUE TITLE
Webhook subscriptions do not work after restart

### ISSUE THREAD

**Issue by nguyer** [hyperledger-labs/firefly#115]
**Expected behavior:**
Webhook subscriptions work the same before/after a restart.

**Observed behavior:**
Webhook subscriptions appear not to send HTTP requests after restarting FireFly core

**Steps to reproduce:**
- Start a new stack
- Create a webhook subscription
- Send a message to test that a webhook is successfully received from the other node
- Stop/start the stack again
- Send another message that should be sent to the webhook - it appears to never arrive

Deleting and re-creating the webhook subscription again appears to work

**Comment by hfuss** [comment]
With deploying FireFly on Kubernetes, @RichBuConsenys mentioned this as potential issue as pods could get restarted / rescheduled at any point.

I was wanting a bit more context of how this occurs at all, is this an issue w/ FireFly not properly persisting the subscription to the DB? Or is it a result of not having persistent storage for a particular directory as part of the FireFly deployment made via the CLI?

**Comment by nguyer** [comment]
I am about to go back to debugging this one, but I _think_ there may actually be an issue with `firefly-ethconnect` itself, and this is a symptom of that issue. It appears that when I stop and start an environment, the very first message doesn't go through at all. It appears that `firefly-ethconnect` is not emitting the event to `firefly`. I think that behavior causes the behavior described in this GitHub issue because the message never completes. Still need to do more investigation on this one though. It's what I'm tackling next.
