### ISSUE TITLE
Sending an empty response.body doesn't match standard HTTP.

### ISSUE THREAD

**Issue by RichBuConsenys** [hyperledger-labs/firefly#133]
When Firefly is returning an empty response, there are two ways it's different from a standard HTTP that another connection is producing.

**Comment by RichBuConsenys** [comment]
this is a standard response from a go HTTP to go HTTP connection.  First, the body is set to http.noBody.  Secondly, the ContentLength is set to 0.
![image](https://user-images.githubusercontent.com/80536434/125967000-6b9eeaab-1586-453c-bc10-ccacb7ed7ab6.png)

what firefly returns instead is http.bodyEOFSignal and then ContentLength is set to a number other than zero.
![image](https://user-images.githubusercontent.com/80536434/125967239-5034e274-89d4-4c5e-9e53-48c0bbacc84b.png)

**Comment by nguyer** [comment]
Thanks for reporting this @RichBuConsenys. Can you please list the steps to reproduce this scenario? Thanks!

**Comment by nguyer** [comment]
@RichBuConsenys Is this still an issue? I'm happy to take a look at it, but I still have not been able to reproduce the issue without some more info on it.
